[package]
name = "zapalloc"
version = "0.0.1"
edition = "2021"
authors = ["Niland Schumacher <naschuma@ucsc.edu>"]
description = "zippy allocator program"
homepage = "https://github.com/nilandasd/Zap"
include = ["/src"]
readme = "README.md"
license = "MIT"

[dependencies]
